#
# FusionAuth Jekyll config
#
title: Home - FusionAuth
email: dev@fusionauth.io
description: >-
  FusionAuth is web-scale Identity for modern apps. It is a secure single-tenant solution that deploys on-premises or in a private cloud.
baseurl: ""
url: "https://fusionauth.io"
twitter_username: fusionauth
github_username:  FusionAuth
source: site
host: 0.0.0.0

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge
plugins:
 - jekyll-asciidoc
 - jekyll-feed
 - jekyll-paginate-v2
 - jekyll-autoprefixer
exclude:
 - docs/src/templates
asciidoctor:
  template_dir: site/docs/src/templates/haml
  base_dir: site
  attributes:
    icons: font
    #    attribute-missing: drop-line
    #    attribute-undefined: drop
    imagesdir: /assets/img/docs
    sectnums: ''
    # Select Pygments for highlighting but disable the Jekyll-Asciidoc's bullshit plugin that generates the CSS file by
    # setting the stylesheet to empty
    source-highlighter: pygments
    pygments-stylesheet:
    stylesdir: /assets/css
    -table-caption:
pagination:
  collection: 'posts'
  enabled: true
  per_page: 5
  permalink: '/page:num/'
  sort_reverse: true
  trail:
    before: 4
    after: 5
sass:
  style: compressed
