#
# FusionAuth Jekyll config
#
title: FusionAuth
email: dev@fusionauth.io
description: >-
  FusionAuth is web-scale Identity for modern apps. It is a secure single-tenant solution that deploys on-premises or in a private cloud.
baseurl: ""
url: "https://fusionauth.io"
twitter_username: fusionauth
github_username:  FusionAuth
source: site
host: 0.0.0.0
cookiebot_id: "2ad8271e-3164-4e6f-9b58-3711b5051068"

# Share images
defaults:
  -
    scope:
      path: "/docs"
    values:
      heroHeader: false
      image: share/docs.png
  -
    scope:
      path: "/learn"
    values:
      heroHeader: false
      image: share/expert-advice.png
  -
    scope:
      path: "/features"
    values:
      heroHeader: false
      image: share/features.png
  -
    scope:
      path: ""
    values:
      heroHeader: false
      image: share/default.png

# Build settings
permalink: pretty
markdown: kramdown
highlighter: rouge
plugins:
 - jekyll-asciidoc
 - jekyll-feed
 - jekyll-paginate-v2
 - jekyll-redirect-from
exclude:
 - docs/src/templates
asciidoctor:
  template_dir: site/docs/src/templates/haml
  base_dir: site
  attributes:
    icons: font
    #    attribute-missing: drop-line
    #    attribute-undefined: drop
    imagesdir: /assets/img/docs
    # Select Pygments for highlighting but disable the Jekyll-Asciidoc's bullshit plugin that generates the CSS file by
    # setting the stylesheet to empty
    source-highlighter: pygments
    pygments-stylesheet:
    stylesdir: /assets/css
    -table-caption:
pagination:
  collection: 'posts'
  enabled: true
  per_page: 5
  permalink: '/page:num/'
  sort_reverse: true
  trail:
    before: 3
    after: 3

algolia:
  application_id: 'MN6ZCVNV21'
  index_name: 'website'
  search_only_api_key: 'e65ffc9f8bb352def753e7614de78416'
  files_to_exclude: []
  nodes_to_index: 'p,dt,dd'
  extensions_to_index:
    - md
    - adoc
    - html
