# Checks asciidoc sanity and also for remote includes
name: asciidoc_check
on: 

## astro migration
#  pull_request:
#    paths:
#      - 'site/docs/v1/**.adoc'
#      - '.github/workflows/asciidoccheck.yml'
##

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_asciidoc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build website
        run: |
          bundle exec jekyll build > build.out 2>&1 || true
        shell: bash
      # if we see any include file warnings, error
      - name: Check for include file warnings.
        run: |
          exit `grep -c 'WARNING: include file is outside of jail' build.out`
        shell: bash
      - name: Check for other warnings.
        run: |
          exit `grep -c 'WARNING: ' build.out`
        shell: bash
      # invert the results of the find command. If we find anything, we want to fail. Otherwise succeed.
      # more here: https://stackoverflow.com/questions/367069/how-can-i-negate-the-return-value-of-a-process
      - name: Check for broken internal asciidoctor links in output
        run: |
          ! find _site/docs -type f|xargs grep -l 'BROKEN LINK'
        shell: bash
      - name: Check for broken includes or other directive issues
        run: |
          ! find _site/docs -type f|xargs grep -l 'Unresolved directive'
        shell: bash
      - name: Check for broken external asciidoctor links in source
        run: |
          ! find site/docs -type f -name "*.adoc"|xargs egrep '^/docs/v1/|[^:]/docs/v1/'|grep -v RSS|grep -v '{% include'
          # ignore lines including the word RSS since those have an href, not a link:
        shell: bash
      - name: Check for broken remote include messages in output
        run: |
          ! find _site -type f|xargs grep -l 'Unresolved directive in'
        shell: bash
