# Checks cloudfront function for correctness
name: cloudfront_function_check
on: 

## astro migration
#  pull_request:
#    paths:
#      - 'src/cloudfront/fusionauth-website-request-handler.js'
#      - '.github/workflows/cloudfrontfunctioncheck.yml'
##

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cloudfront_function_check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'astro/package-lock.json'
      - name: Check cloudfront function is syntactically correct.
        run: node --check src/cloudfront/fusionauth-website-request-handler.js
        shell: bash
