# This shrinks any pngs that are new in this PR, runs on push.
name: Shrink images
on:
  push:
    branches-ignore:
      - master

jobs:
  shrink:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      TINYPNG_API_KEY: "${{ secrets.TINYPNG_API_KEY }}"
    steps:
      - uses: actions/checkout@v3
      - name: Shrink images using tinypng
        run: |
          bash ./src/new-images-shrink.sh
        shell: bash
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Shrink images
