# This is workflow for spell checking using PySpelling lib (https://pypi.org/project/pyspelling/)
name: spellcheck_website
on: 
  # run once a weekday at ~noon MT 
  schedule:
    - cron: '31 17 * * 2,4'
  # can run on push too, but takes too long right now https://github.com/tj-actions/changed-files might help, but then we need to convert from the changed source files to html directories. might be a nice project in the future.
  # push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build website for spellcheck
        run: |
          bundle exec jekyll build || true 
        shell: bash
      # Spellcheck
      - uses: igsekor/pyspelling-any@v0.0.2
        name: Spellcheck
      # invert the results of the find command. If we find anything, we want to fail. Otherwise succeed.
      # more here: https://stackoverflow.com/questions/367069/how-can-i-negate-the-return-value-of-a-process
      - name: Check for broken asciidoctor links
        run: |
          ! find _site/docs -type f|xargs grep -l 'BROKEN LINK'
        shell: bash
